# --> Catppuccin (Everforest Dark Hard)
set -gq @thm_bg "#1e2326"
set -gq @thm_fg "#d3c6aa"

# Colors
set -gq @thm_rosewater "#e69875"
set -gq @thm_flamingo "#e67e80"
set -gq @thm_pink "#d699b6"
set -gq @thm_mauve "#d699b6"
set -gq @thm_red "#e67e80"
set -gq @thm_maroon "#e67e80"
set -gq @thm_peach "#e69875"
set -gq @thm_yellow "#dbbc7f"
set -gq @thm_green "#a7c080"
set -gq @thm_teal "#83c092"
set -gq @thm_sky "#7fbbb3"
set -gq @thm_sapphire "#7fbbb3"
set -gq @thm_blue "#7fbbb3"
set -gq @thm_lavender "#d699b6"

# Surfaces and overlays
set -gq @thm_subtext_1 "#9da9a0"
set -gq @thm_subtext_0 "#859289"
set -gq @thm_overlay_2 "#7a8478"
set -gq @thm_overlay_1 "#4f5b58"
set -gq @thm_overlay_0 "#495156"
set -gq @thm_surface_2 "#414b50"
set -gq @thm_surface_1 "#374145"
set -gq @thm_surface_0 "#2e383c"
set -gq @thm_mantle "#272e33"
set -gq @thm_crust "#1e2326"
