# --> Catppuccin (Gruvbox Light)
set -gq @thm_bg "#fbf1c7"
set -gq @thm_fg "#3c3836"

# Colors
set -gq @thm_rosewater "#7c6f64"
set -gq @thm_flamingo "#7c6f64"
set -gq @thm_pink "#b16286"
set -gq @thm_mauve "#8f3f71"
set -gq @thm_red "#cc241d"
set -gq @thm_maroon "#9d0006"
set -gq @thm_peach "#d65d0e"
set -gq @thm_yellow "#d79921"
set -gq @thm_green "#98971a"
set -gq @thm_teal "#689d6a"
set -gq @thm_sky "#458588"
set -gq @thm_sapphire "#076678"
set -gq @thm_blue "#458588"
set -gq @thm_lavender "#b16286"

# Surfaces and overlays
set -gq @thm_subtext_1 "#665c54"
set -gq @thm_subtext_0 "#7c6f64"
set -gq @thm_overlay_2 "#928374"
set -gq @thm_overlay_1 "#a89984"
set -gq @thm_overlay_0 "#bdae93"
set -gq @thm_surface_2 "#d5c4a1"
set -gq @thm_surface_1 "#ebdbb2"
set -gq @thm_surface_0 "#f2e5bc"
set -gq @thm_mantle "#f2e5bc"
set -gq @thm_crust "#fbf1c7"
