# This config uses the catppuccin tmux plugin with a custom Gruvbox Light Hard palette mapping.
#
# It won't work unless you've copied the theme file in `themes` into the catppuccin plugin dir:
# cp ~/.config/tmux/themes/gruvbox-light-hard.conf ~/.config/tmux/plugins/tmux/themes/catppuccin_gruvbox_light_hard_tmux.conf
#
# Palette source: https://github.com/morhetz/gruvbox

set -g @catppuccin_flavor "gruvbox_light_hard"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"
set -g @catppuccin_status_modules_right ""

# Load the UI.
source-file ~/.config/tmux/tmux.ui.conf
