# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_mocha'
format = "$hostname$directory($git_branch)$git_status $character"

[character]
success_symbol = "[[󰄛](green) >](peach)"
error_symbol = "[[󰄛](red) >](peach)"
vimcmd_symbol = "[󰄛 <](subtext1)" # For use with zsh-vi-mode

[directory]
format = "[\\[$path\\]]($style)"
read_only = " 󰌾"
style = "bold sapphire"

[git_branch]
format = " [\\($symbol$branch(:$remote_branch)\\)]($style) "
style = "bold mauve"
symbol = " "

[git_status]
format = "[$all_status]($style)"
style = "bold maroon"

[hostname]
format = " [$ssh_symbol$hostname]($style) "
ssh_only = false
ssh_symbol = " "
style = "bold teal"

[memory_usage]
symbol = "󰍛 "

[username]
format = "[$user]($style)"
show_always = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
