color = "true"
mode = "file"
sourceDir = "~/code/nickcorin/dotfiles"

[diff]
    pager = "bat"

[edit]
    apply = true
    command = "nvim"
    minDuration = "1s"
    watch = true

[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

[onepassword]
    command = "op"
    cache = true

