sourceDir = "~/code/dotfiles"

[diff]
    pager = "bat"

[edit]
    command = "nvim"
    watch = true
    minDuration = "1s"

[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

[onepassword]
    command = "op"
    cache = true

