# Chezmoi configuration

[edit]
command = "nvim"

[diff]
pager = "bat"

# Custom commands
[scriptEnv]
CHEZMOI_BREW_RETRY = "true"

# Aliases for common tasks
[alias]
brew-install = "apply --include=scripts/run_always_20-ensure-packages.sh.tmpl"
brew-force = "apply --include=scripts/run_always_20-ensure-packages.sh.tmpl --force"