import = [
"~/.config/alacritty/themes/gruvbox-material-dark-hard.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "Monaspace Argon"
style = "Bold"

[font.bold_italic]
family = "Monaspace Argon"
style = "Bold Italic"

[font.italic]
family = "Monaspace Argon"
style = "Italic"

[font.normal]
family = "Monaspace Argon"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 1000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = false
opacity = 1
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5
