-- SPDX-License-Identifier: WTFPL
-- Adapted from Kirill Chibisov's Alacritty colorscheme:
-- https://git.sr.ht/~kchibisov/dotfiles/tree/main/item/.config/nvim/colors/alacritty.vim

vim.o.background = "dark"
vim.cmd.highlight("clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.cmd.syntax("reset")
end
vim.g.colors_name = "alacritty"

local palette = {
	background = { hex = "#181818", index = 0 },
	red = { hex = "#ac4242", index = 1 },
	green = { hex = "#90a959", index = 2 },
	yellow = { hex = "#f4bf75", index = 3 },
	blue = { hex = "#6a9fb5", index = 4 },
	magenta = { hex = "#aa759f", index = 5 },
	cyan = { hex = "#75b5aa", index = 6 },
	foreground = { hex = "#d8d8d8", index = 7 },
	muted = { hex = "#6b6b6b", index = 8 },
	bright_red = { hex = "#c55555", index = 9 },
	bright_green = { hex = "#aac474", index = 10 },
	bright_yellow = { hex = "#feca88", index = 11 },
	bright_blue = { hex = "#82b8c8", index = 12 },
	bright_magenta = { hex = "#c28cb8", index = 13 },
	bright_cyan = { hex = "#93d3c3", index = 14 },
	bright_white = { hex = "#f8f8f8", index = 15 },
	brown = { hex = "#8f5536", index = 87 },
	orange = { hex = "#d28445", index = 166 },
	surface = { hex = "#262626", index = 236 },
	selection = { hex = "#333333", index = 237 },
	diff_add = { hex = "#052200", index = 22 },
	diff_change = { hex = "#0e3337", index = 23 },
	diff_text = { hex = "#405963", index = 24 },
	diff_delete = { hex = "#442220", index = 52 },
}

local ansi = {
	"background",
	"red",
	"green",
	"yellow",
	"blue",
	"magenta",
	"cyan",
	"foreground",
	"muted",
	"bright_red",
	"bright_green",
	"bright_yellow",
	"bright_blue",
	"bright_magenta",
	"bright_cyan",
	"bright_white",
}
for index, name in ipairs(ansi) do
	vim.g["terminal_color_" .. (index - 1)] = palette[name].hex
end

local highlights = {
	Added = { fg = "bright_green" },
	Bold = { bold = true },
	Changed = { fg = "bright_yellow" },
	ColorColumn = { bg = "surface" },
	ComplMatchIns = { fg = "yellow", bold = true },
	Conceal = { fg = "muted" },
	CurSearch = { fg = "background", bg = "yellow", bold = true },
	Cursor = { fg = "background", bg = "foreground" },
	CursorColumn = { bg = "surface" },
	CursorLine = { bg = "surface" },
	CursorLineNr = { fg = "bright_white", bg = "surface", bold = true },
	Debug = { fg = "green" },
	Directory = { fg = "blue", bold = true },
	EndOfBuffer = { fg = "background", bg = "background" },
	Error = { fg = "foreground", bg = "red" },
	ErrorMsg = { fg = "red" },
	Exception = { fg = "red", bold = true },
	FloatBorder = { fg = "muted", bg = "background" },
	FloatTitle = { fg = "yellow", bg = "background", bold = true },
	FoldColumn = { fg = "cyan", bg = "surface" },
	Folded = { fg = "muted", bg = "surface", italic = true },
	IncSearch = { fg = "background", bg = "yellow" },
	Italic = { italic = true },
	LineNr = { fg = "muted", bg = "background" },
	Macro = { fg = "red" },
	MatchParen = { fg = "blue", underline = true },
	ModeMsg = { fg = "green" },
	MoreMsg = { fg = "green" },
	NonText = { fg = "muted" },
	Normal = { fg = "foreground", bg = "background" },
	NormalFloat = { fg = "foreground", bg = "background" },
	NormalNC = { fg = "foreground", bg = "background" },
	Pmenu = { fg = "foreground", bg = "surface" },
	PmenuBorder = { fg = "muted", bg = "surface" },
	PmenuExtra = { fg = "muted", bg = "surface" },
	PmenuExtraSel = { fg = "muted", bg = "selection" },
	PmenuKind = { fg = "cyan", bg = "surface" },
	PmenuKindSel = { fg = "cyan", bg = "selection" },
	PmenuMatch = { fg = "yellow", bold = true },
	PmenuMatchSel = { fg = "bright_yellow", bold = true },
	PmenuSbar = { bg = "surface" },
	PmenuSel = { fg = "foreground", bg = "selection", bold = true },
	PmenuShadow = { bg = "background", blend = 50 },
	PmenuShadowThrough = { bg = "background", blend = 70 },
	PmenuThumb = { bg = "muted" },
	Question = { fg = "blue" },
	QuickFixLine = { bg = "surface", bold = true },
	Removed = { fg = "bright_red" },
	Search = { fg = "background", bg = "red" },
	SignColumn = { fg = "muted", bg = "background" },
	SpecialKey = { fg = "muted" },
	StatusLine = { fg = "foreground", bg = "surface", bold = true },
	StatusLineNC = { fg = "muted", bg = "surface" },
	StatusLineTerm = { fg = "foreground", bg = "surface", bold = true },
	StatusLineTermNC = { fg = "muted", bg = "surface" },
	Substitute = { fg = "background", bg = "yellow" },
	TabLine = { fg = "muted", bg = "surface" },
	TabLineFill = { fg = "muted", bg = "surface" },
	TabLineSel = { fg = "green", bg = "surface", bold = true },
	Title = { fg = "blue", bold = true },
	Underlined = { fg = "cyan", underline = true },
	Visual = { bg = "selection" },
	VisualNOS = { bg = "selection", underline = true },
	WarningMsg = { fg = "yellow" },
	Whitespace = { fg = "selection", nocombine = true },
	WildMenu = { fg = "background", bg = "yellow" },
	WinBar = { fg = "foreground", bg = "surface", bold = true },
	WinBarNC = { fg = "muted", bg = "surface" },
	WinSeparator = { fg = "surface", bg = "background" },

	Boolean = { fg = "orange" },
	Character = { fg = "orange" },
	Comment = { fg = "muted", italic = true },
	Conditional = { fg = "magenta" },
	Constant = { fg = "orange" },
	Define = { fg = "magenta" },
	Delimiter = { fg = "brown" },
	Float = { fg = "orange" },
	Function = { fg = "blue" },
	Identifier = { fg = "yellow" },
	Include = { fg = "blue" },
	Keyword = { fg = "magenta" },
	Label = { fg = "yellow" },
	Number = { fg = "orange" },
	Operator = { fg = "foreground" },
	PreProc = { fg = "yellow" },
	Punctuation = { fg = "foreground" },
	Repeat = { fg = "magenta" },
	Special = { fg = "cyan" },
	SpecialChar = { fg = "brown" },
	Statement = { fg = "red", bold = true },
	StorageClass = { fg = "yellow" },
	String = { fg = "green" },
	Structure = { fg = "magenta" },
	Tag = { fg = "yellow" },
	Todo = { fg = "bright_red", bold = true },
	Type = { fg = "yellow" },
	Typedef = { fg = "yellow" },
	Variable = { fg = "foreground" },

	DiffAdd = { bg = "diff_add" },
	DiffChange = { bg = "diff_change" },
	DiffDelete = { bg = "diff_delete" },
	DiffText = { bg = "diff_text" },

	DiagnosticError = { fg = "red" },
	DiagnosticHint = { fg = "cyan" },
	DiagnosticInfo = { fg = "blue" },
	DiagnosticOk = { fg = "green" },
	DiagnosticWarn = { fg = "yellow" },
	DiagnosticSignError = { fg = "red", bg = "background" },
	DiagnosticSignHint = { fg = "cyan", bg = "background" },
	DiagnosticSignInfo = { fg = "blue", bg = "background" },
	DiagnosticSignOk = { fg = "green", bg = "background" },
	DiagnosticSignWarn = { fg = "yellow", bg = "background" },
	DiagnosticUnnecessary = { fg = "muted" },
	DiagnosticUnderlineError = { sp = "red", undercurl = true },
	DiagnosticUnderlineHint = { sp = "cyan", undercurl = true },
	DiagnosticUnderlineInfo = { sp = "blue", undercurl = true },
	DiagnosticUnderlineOk = { sp = "green", undercurl = true },
	DiagnosticUnderlineWarn = { sp = "yellow", undercurl = true },

	GitSignsAdd = { fg = "bright_green", bg = "background" },
	GitSignsChange = { fg = "bright_yellow", bg = "background" },
	GitSignsDelete = { fg = "bright_red", bg = "background" },
	GitSignsStagedAdd = { fg = "muted", bg = "background" },
	GitSignsStagedChange = { fg = "muted", bg = "background" },
	GitSignsStagedDelete = { fg = "muted", bg = "background" },
	LspSignatureActiveParameter = { fg = "bright_yellow", bg = "surface", bold = true },
	RainbowDelimiterBlue = { fg = "blue" },
	RainbowDelimiterCyan = { fg = "cyan" },
	RainbowDelimiterGreen = { fg = "green" },
	RainbowDelimiterOrange = { fg = "orange" },
	RainbowDelimiterRed = { fg = "red" },
	RainbowDelimiterViolet = { fg = "magenta" },
	RainbowDelimiterYellow = { fg = "yellow" },
	SnacksDashboardDesc = { fg = "foreground" },
	SnacksDashboardFooter = { fg = "muted", italic = true },
	SnacksDashboardHeader = { fg = "blue" },
	SnacksDashboardIcon = { fg = "cyan" },
	SnacksDashboardKey = { fg = "yellow", bold = true },
	SnacksDashboardSpecial = { fg = "magenta" },
	FFFGitDeleted = { fg = "bright_red" },
	FFFGitIgnored = { fg = "muted" },
	FFFGitModified = { fg = "bright_yellow" },
	FFFGitRenamed = { fg = "bright_magenta" },
	FFFGitSignDeleted = { fg = "bright_red" },
	FFFGitSignDeletedSelected = { fg = "bright_red", bg = "selection" },
	FFFGitSignIgnored = { fg = "muted" },
	FFFGitSignIgnoredSelected = { fg = "muted", bg = "selection" },
	FFFGitSignModified = { fg = "bright_yellow" },
	FFFGitSignModifiedSelected = { fg = "bright_yellow", bg = "selection" },
	FFFGitSignRenamed = { fg = "bright_magenta" },
	FFFGitSignRenamedSelected = { fg = "bright_magenta", bg = "selection" },
	FFFGitSignStaged = { fg = "bright_green" },
	FFFGitSignStagedSelected = { fg = "bright_green", bg = "selection" },
	FFFGitSignUntracked = { fg = "bright_green" },
	FFFGitSignUntrackedSelected = { fg = "bright_green", bg = "selection" },
	FFFGitStaged = { fg = "bright_green" },
	FFFGitUntracked = { fg = "bright_green" },
	SnacksPickerGitStatusModified = { fg = "bright_yellow" },
	SnacksPickerGitStatusRenamed = { fg = "bright_magenta" },
	SnacksPickerGitStatusStaged = { fg = "bright_green" },
	SnacksPickerGitStatusUntracked = { fg = "bright_green" },
}

local links = {
	["@attribute"] = "PreProc",
	["@boolean"] = "Boolean",
	["@character"] = "Character",
	["@comment"] = "Comment",
	["@comment.documentation"] = "Comment",
	["@constant"] = "Constant",
	["@constant.builtin"] = "Constant",
	["@constructor"] = "Type",
	["@function"] = "Function",
	["@function.builtin"] = "Function",
	["@function.call"] = "Function",
	["@function.macro"] = "Macro",
	["@keyword"] = "Keyword",
	["@keyword.conditional"] = "Conditional",
	["@keyword.function"] = "Keyword",
	["@keyword.import"] = "Include",
	["@keyword.repeat"] = "Repeat",
	["@keyword.return"] = "Keyword",
	["@label"] = "Label",
	["@markup.heading"] = "Title",
	["@markup.link"] = "Underlined",
	["@markup.link.url"] = "Underlined",
	["@markup.list"] = "Special",
	["@markup.raw"] = "String",
	["@method"] = "Function",
	["@module"] = "Include",
	["@number"] = "Number",
	["@number.float"] = "Float",
	["@operator"] = "Operator",
	["@property"] = "Identifier",
	["@punctuation"] = "Punctuation",
	["@punctuation.bracket"] = "Punctuation",
	["@punctuation.delimiter"] = "Delimiter",
	["@string"] = "String",
	["@string.escape"] = "SpecialChar",
	["@string.regexp"] = "String",
	["@tag"] = "Tag",
	["@tag.attribute"] = "Identifier",
	["@tag.delimiter"] = "Delimiter",
	["@type"] = "Type",
	["@type.builtin"] = "Type",
	["@variable"] = "Variable",
	["@variable.builtin"] = "Keyword",
	["@variable.member"] = "Identifier",
	["@variable.parameter"] = "Variable",

	["@lsp.mod.constant"] = "Number",
	["@lsp.type.boolean"] = "Boolean",
	["@lsp.type.builtinType"] = "Type",
	["@lsp.type.character"] = "Character",
	["@lsp.type.class"] = "Type",
	["@lsp.type.comment"] = "Comment",
	["@lsp.type.decorator"] = "PreProc",
	["@lsp.type.enum"] = "Type",
	["@lsp.type.enumMember"] = "Function",
	["@lsp.type.event"] = "Special",
	["@lsp.type.function"] = "Function",
	["@lsp.type.interface"] = "Type",
	["@lsp.type.keyword"] = "Keyword",
	["@lsp.type.macro"] = "Macro",
	["@lsp.type.method"] = "Function",
	["@lsp.type.modifier"] = "StorageClass",
	["@lsp.type.namespace"] = "Include",
	["@lsp.type.number"] = "Number",
	["@lsp.type.operator"] = "Operator",
	["@lsp.type.parameter"] = "Variable",
	["@lsp.type.property"] = "Identifier",
	["@lsp.type.regexp"] = "String",
	["@lsp.type.selfKeyword"] = "Keyword",
	["@lsp.type.selfTypeKeyword"] = "Type",
	["@lsp.type.string"] = "String",
	["@lsp.type.struct"] = "Type",
	["@lsp.type.type"] = "Type",
	["@lsp.type.typeParameter"] = "Typedef",
	["@lsp.type.variable"] = "Variable",
	["@lsp.typemod.comment.documentation"] = "Comment",

	["@lsp.mod.callable.rust"] = "Function",
	["@lsp.mod.unsafe.rust"] = "Exception",
	["@lsp.type.decorator.rust"] = "PreProc",
	["@lsp.type.macro.rust"] = "Macro",
	["@lsp.type.union.rust"] = "Exception",
	["@lsp.typemod.function.constant.rust"] = "Function",

	FFFFileInfoLabel = "Comment",
	FFFFileInfoPath = "Directory",
	FFFFileInfoSection = "Title",
	FFFFileInfoSeparator = "FloatBorder",
	FFFFileInfoSize = "Number",
	FFFFileInfoType = "Type",
	FFFFileInfoValueDim = "NonText",
	GitSignsCurrentLineBlame = "NonText",
	SnacksDashboardNormal = "Normal",
	SnacksPickerMatch = "IncSearch",
	SnacksPickerPrompt = "Question",
	diffAdded = "String",
	diffRemoved = "Constant",
	luaFunc = "Function",
	luaOperator = "Conditional",
	markdownCodeDelimiter = "Delimiter",
	markdownH1Delimiter = "Title",
	markdownH2Delimiter = "Title",
	markdownH3Delimiter = "Title",
	markdownH4Delimiter = "Title",
	pythonOperator = "Statement",
	rustCommentLineDoc = "Comment",
	rustEnumVariant = "Function",
	rustLifetime = "Macro",
	rustOperator = "Function",
	rustSelf = "Keyword",
	rustStorage = "Keyword",
	tomlKey = "Identifier",
	vimOper = "Normal",
}

local function resolve(spec)
	local resolved = vim.deepcopy(spec)
	for _, attribute in ipairs({ "fg", "bg", "sp" }) do
		local name = resolved[attribute]
		if name then
			local color = assert(palette[name], "unknown Alacritty color: " .. name)
			resolved[attribute] = color.hex
			if attribute ~= "sp" then
				resolved["cterm" .. attribute] = color.index
			end
		end
	end
	return resolved
end

for group, spec in pairs(highlights) do
	vim.api.nvim_set_hl(0, group, resolve(spec))
end
for group, target in pairs(links) do
	vim.api.nvim_set_hl(0, group, { link = target })
end
