installers:
  curl:
    cmd: curl -fsSL $1 | bash -E -
    available: command -v curl &>/dev/null
    skip_check: command -v $1 &>/dev/null

  homebrew:
    cmd: brew install $1
    available: command -v brew &>/dev/null
    skip_check: brew list --formula $1 &>/dev/null

  homebrew_cask:
    cmd: brew install --cask $1
    available: command -v brew &>/dev/null
    skip_check: brew list --cask $1 &>/dev/null

  npm:
    cmd: npm install -g $1
    available: command -v npm &>/dev/null
    skip_check: npm list -g $1 &>/dev/null

stages:
  - setup:
      darwin:
        - name: brew
          installer: curl
          arg: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

        - name: fnm
          installer: homebrew
          post: fnm install --lts && eval "$(fnm env)" && exec $SHELL

  - install:
      all:
        - name: "@google/gemini-cli"
          installer: npm

        - name: "@anthropic-ai/claude-code"
          installer: npm

        - name: bun
          installer: curl
          arg: https://bun.sh/install

        - name: eslint
          installer: npm

        - name: prettier
          installer: npm

        - name: typescript
          installer: npm

      darwin:
        - name: dotenvx
          installer: homebrew
          pre: "brew tap dotenvx/brew"

        - name: awscli
          installer: homebrew

        - name: bat
          installer: homebrew

        - name: block-goose-cli
          installer: homebrew

        - name: buf
          installer: homebrew

        - name: chezmoi
          installer: homebrew

        - name: curl
          installer: homebrew

        - name: eza
          installer: homebrew

        - name: fastfetch
          installer: homebrew

        - name: fd
          installer: homebrew

        - name: ffmpeg
          installer: homebrew

        - name: fzf
          installer: homebrew

        - name: gh
          installer: homebrew

        - name: git
          installer: homebrew

        - name: go
          installer: homebrew

        - name: go-task
          installer: homebrew

        - name: gofumpt
          installer: homebrew

        - name: goimports
          installer: homebrew

        - name: gotop
          installer: homebrew

        - name: htop
          installer: homebrew

        - name: imagemagick
          installer: homebrew

        - name: jq
          installer: homebrew

        - name: lazygit
          installer: homebrew

        - name: lua-language-server
          installer: homebrew

        - name: mutt
          installer: homebrew

        - name: neovim
          installer: homebrew

        - name: ollama
          installer: homebrew

        - name: opencode
          installer: homebrew
          arg: sst/tap/opencode

        - name: protobuf
          installer: homebrew

        - name: python
          installer: homebrew

        - name: ripgrep
          installer: homebrew

        - name: rust-analyzer
          installer: homebrew

        - name: sesh
          installer: homebrew

        - name: starship
          installer: homebrew

        - name: tig
          installer: homebrew

        - name: tmux
          installer: homebrew

        - name: tpm
          installer: homebrew

        - name: tree
          installer: homebrew

        - name: typst
          installer: homebrew

        - name: uv
          installer: homebrew

        - name: vim
          installer: homebrew

        - name: wget
          installer: homebrew

        - name: yq
          installer: homebrew

        - name: yt-dlp
          installer: homebrew

        - name: zig
          installer: homebrew

        - name: zoxide
          installer: homebrew

        - name: zsh-autosuggestions
          installer: homebrew

        - name: zsh-syntax-highlighting
          installer: homebrew

        - name: 1password-cli
          installer: homebrew_cask

        - name: alacritty
          installer: homebrew_cask

        - name: block-goose
          installer: homebrew_cask

        - name: corelocationcli
          installer: homebrew_cask

        - name: docker
          installer: homebrew_cask

        - name: font-fira-code-nerd-font
          installer: homebrew_cask

        - name: font-monaspace
          installer: homebrew_cask

        - name: font-noto-nerd-font
          installer: homebrew_cask

        - name: font-roboto-mono-nerd-font
          installer: homebrew_cask

        - name: font-sf-mono-nerd-font-ligaturized
          installer: homebrew_cask

        - name: font-ubuntu-mono-nerd-font
          installer: homebrew_cask

        - name: ghostty
          installer: homebrew_cask

        - name: keybase
          installer: homebrew_cask

        - name: keycastr
          installer: homebrew_cask

        - name: keepingyouawake
          installer: homebrew_cask

        - name: mactex
          installer: homebrew_cask

        - name: obsidian
          installer: homebrew_cask

        - name: raycast
          installer: homebrew_cask
